import React, { useEffect, useRef, useState } from "react";
import firebase from "firebase";
import configs from "../configs/dbConfigs";
import { Button } from "@material-ui/core";
import mapboxgl from "mapbox-gl";

export default function Test() {
  if (!firebase.apps.length) {
    firebase.initializeApp(configs);
  }

  const db = firebase.firestore();
  const [data, setData] = useState([]);
  const [loc, setLoc] = useState({ lng: 5, lat: 34, zoom: 2 });

  useEffect(() => {
    db.collection("test").onSnapshot((snapshot) => {
      setData(snapshot.docs.map((doc, idx) => ({ key: idx, ...doc.data() })));
    });
  }, []);

  const testMapRef = useRef(null);

  const map = new mapboxgl.Map({
    container: testMapRef.current,
    style: "mapbox://styles/mapbox/streets-v11",
    center: [loc.lng, loc.lat],
    zoom: loc.zoom,
  });

  mapboxgl.accessToken = "MAPBOX_ACCESS_TOKEN";

  return (
    <>
      <link
        href="https://api.tiles.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css"
        rel="stylesheet"
      />
      <div ref={(el) => (testMapRef = el)}></div>
      <ul>
        {data.map((item) => (
          <li key={item.key}>{item.name}</li>
        ))}
      </ul>
      <Button
        onClick={() => {
          db.collection("fact_1").add([
            { title: "A High Order Accuracy Computational Tool for Unsteady Turbulent Flows and Acoustics", award amount: 69675.000000 }, 
            { title: "Computations of Separated High-Enthalpy Hypersonic Flows: Development of RANS and Variable-Resolution PANS Approaches", award amount: 70575.000000 }, 
            { title: "A High Order Accuracy Computational Tool for Unsteady Turbulent Flows and Acoustics", award amount: 0.000000 }, 
            { title: "Oxygen-Methane Thruster", award amount: 50000.000000 }, 
            { title: "Acoustic Igniter", award amount: 99994.000000 }, 
            { title: "Acoustic Igniter", award amount: 599994.000000 }, 
            { title: "Dual Use Catalytically Initiated Combustor (CIC) for Rocket Engine Ignition and Thruster Applications", award amount: 99257.000000 }, 
            { title: "Low Cost High Efficiency Pressurization System for Responsive Launch Operations", award amount: 124351.000000 }, 
            { title: "Intelligent Agents for Improved Ground-Test Operations", award amount: 100000.000000 }, 
            { title: "Mesh Adaptation and Shape Optimization on Unstructured Meshes", award amount: 124986.000000 }, 
            { title: "Novel Solar Cell Nanotechnology for Improved Efficiency and Radiation Hardness", award amount: 599985.600000 }, 
            { title: "Advanced Nongray Radiation Module in the LOCI Framework for Combustion CFD", award amount: 99921.000000 }, 
            { title: "Advanced Nongray Radiation Module in the LOCI Framework for Combustion CFD", award amount: 599913.000000 }, 
            { title: "Improved Models and Tools for Prediction of Radiation Effects on Space Electronics in Wide Temperature Range", award amount: 599878.000000 }, 
            { title: "Non-Destructive Detection and Separation of Radiation Damaged Cells in Miniaturized Inexpensive Device", award amount: 99988.000000 }, 
            { title: "Numerical Simulation of Rocket Exhaust Interaction with Lunar Soil", award amount: 99990.430000 }, 
            { title: "Non-Destructive Detection and Separation of Radiation Damaged Cells in Miniaturized Inexpensive Device", award amount: 599929.000000 }, 
            { title: "Numerical Simulation of Rocket Exhaust Interaction with Lunar Soil", award amount: 599998.500000 }, 
            { title: "Aeroservoelastic Modeling", award amount: 99980.000000 }, 
            { title: "An On-Chip Nano-Plasmonics Based Urine Protein Assay Cartridge", award amount: 99993.350000 }, 
            { title: "Fuel/Oxidizer Injector Modeling in Sub- and Super-Critical Regimes for Deep Throttling Cryogenic Engines ", award amount: 99971.000000 }, 
            { title: "An On-Chip Nano-Plasmonics Based Urine Protein Assay Cartridge", award amount: 599892.000000 }, 
            { title: "Compact Controlled Force Crew Exercise System", award amount: 99950.020000 }, 
            { title: "A Comprehensive CFD Tool for Aerothermal Environment Around Space Vehicles", award amount: 99968.000000 }, 
            { title: "Compact Controlled Force Crew Exercise System", award amount: 598964.000000 }, 
            { title: "A Comprehensive CFD Tool for Aerothermal Environment Around Space Vehicles", award amount: 599919.000000 }, 
            { title: "Benchmark Numerical Toolkits for High Performance Computing", award amount: 99965.000000 }, 
            { title: "High-Fidelity Gas and Granular Flow Physics Models for Rocket Exhaust Interaction with Lunar Soil", award amount: 99934.830000 }, 
            { title: "High-Fidelity Gas and Granular Flow Physics Models for Rocket Exhaust Interaction with Lunar Soil", award amount: 499992.000000 }, 
            { title: "Constant Volume Combustion Engine for Planetary Ascent Vehicles", award amount: 99952.000000 }, 
            { title: "Integrated Inflatable Ballute for Planetary Entry", award amount: 99916.000000 }, 
            { title: "Computational Tool for Coupled Simulation of Nonequilibrium Hypersonic Flows with Ablation", award amount: 99999.000000 }, 
            { title: "Improved Design of Radiation Hardened Wide-Temperature Analog and Mixed-Signal Electronics", award amount: 99907.000000 }, 
            { title: "Software for Automated Generation of Reduced Thermal Models for Spacecraft Thermal Control", award amount: 99875.000000 }, 
            { title: "A Miniaturized Sensor for Microbial Monitoring of Spacecraft Water Environment", award amount: 99931.000000 }, 
            { title: "Integrated Inflatable Ballute for Planetary Entry", award amount: 599878.000000 }, 
            { title: "Computational Tool for Coupled Simulation of Nonequilibrium Hypersonic Flows with Ablation", award amount: 599980.000000 }, 
            { title: "Improved Design of Radiation Hardened Wide-Temperature Analog and Mixed-Signal Electronics", award amount: 599897.000000 }, 
            { title: "Software for Automated Generation of Reduced Thermal Models for Spacecraft Thermal Control", award amount: 599963.000000 }, 
            { title: "A Miniaturized Sensor for Microbial Monitoring of Spacecraft Water Environment", award amount: 599966.000000 }, 
            { title: "High Duty Cycle Extended Operation Constant Volume Combustion Engine", award amount: 96337.000000 }, 
            { title: "Free-Surface Modeling of Cryogenic Fluids Using a Higher-Order Unstructured Grid Volume-of-Fluid (VOF) Method", award amount: 99998.000000 }, 
            { title: "Implicit Higher Order Temporal Differencing for Aeroacoustic and CFD Applications", award amount: 99804.000000 }, 
            { title: "Hybrid Approach for Modeling Chemical Kinetics and Turbulence Effects on Combustion-Instability", award amount: 99923.000000 }, 
            { title: "Energy Conservation and Sustainability Technologies for Propellant Conservation", award amount: 99999.000000 }, 
            { title: "High-Fidelity Prediction of Launch Vehicle Liftoff Acoustic Fields", award amount: 99947.000000 }, 
            { title: "Electron Kinetics in Hypersonic Plasmas", award amount: 124954.000000 }, 
            { title: "Eulerian Transported PDF Framework for Scramjet Flowpath Analysis", award amount: 124935.000000 }, 
            { title: "Nonlinear AeroServoElastic Reduced Order Model for Active Structural Control", award amount: 124930.000000 }, 
            { title: "Ionic Liquid Nontoxic Monopropellants for Power-Limited Spacecraft", award amount: 124849.000000 }, 
            { title: "A Multi-disciplinary Tool for Space Launch Systems Propulsion Analysis", award amount: 124955.000000 }, 
            { title: "An Electrochemical Point-of-Care Detector for Reagent-free In-situ Diagnostics of Pathogens", award amount: 124923.000000 }, 
            { title: "Autonomous Multi-Robot Exploration using UWB", award amount: 124914.000000 }, 
            { title: "Radiation-Hardened Memristor-based Memory for Extreme Environments", award amount: 124888.000000 }, 
            { title: "MEMS Based Solutions for an Integrated and Miniaturized Multi-Spectrum Energy Harvesting and Conservation System", award amount: 125000.000000 }, 
            { title: "High-Fidelity Prediction of Launch Vehicle Lift-off Acoustic Environment", award amount: 124769.000000 }, 
            { title: "Particle Flow Physics Modeling for Extreme Environments", award amount: 124972.000000 }, 
            { title: "Power Generating Coverings and Casings", award amount: 121887.000000 }, 
            { title: "Hybrid Guidance System for Relative Navigation", award amount: 599912.000000 }, 
            { title: "Using a Bore Sight Camera as an AR&amp;D Sensor", award amount: 99880.000000 }, 
            { title: "Using a Bore Sight Camera as an AR&amp;D Sensor", award amount: 599934.000000 }, 
            { title: "Ultralightweight Regeneratively Cooled Combustion Chamber for Mars Ascent Vehicles", award amount: 99999.000000 }, 
            { title: "Advanced Ionic Liquid Monopropellant for Payload Ascent Vehicles", award amount: 99915.000000 }, 
            { title: "Application of Advanced Radiation Shielding Materials to Inflatable Structures", award amount: 99321.000000 }, 
            { title: "Carbon Nano-Composite Ablative Rocket Nozzles", award amount: 99683.000000 }, 
            { title: "Low Power Low Cost Igniter for Nonhypergolic Mars Ascent Vehicle", award amount: 99995.000000 }, 
            { title: "Ionic Liquid Epoxy Composite Cryotanks", award amount: 96884.000000 }, 
            { title: "Low Cost Refractory Matrix Composite Thruster for Mars Ascent Vehicles", award amount: 124990.000000 }, 
            { title: "Efficient Conversion of Carbon Dioxide into Methane using 3rd Generation Ionic Liquids", award amount: 124890.000000 }, 
            { title: "Solid Rocket Motor for Ultralow Temperature Operation During the Mars Sample Return Mission", award amount: 124868.000000 }, 
            { title: "Low-Cost Manufacturing Technique for Advanced Regenerative Cooling for In-Space Cryogenic Engines", award amount: 124436.000000 }, 
            { title: "Plasma Reduction of Lunar Regolith for In-Space Fabrication", award amount: 600000.000000 }, 
            { title: "Innovative Molybdenum Alloy for Extreme Operating Conditions", award amount: 99999.000000 }, 
            { title: "Lightweight Exit Cone for Liquid Rocket Engines", award amount: 100000.000000 }, 
            { title: "Lightweight Nozzle Extension for Liquid Rocket Engines", award amount: 600000.000000 }, 
            { title: "High Surface Iridium Anodes for Molten Oxide Electrolysis", award amount: 100000.000000 }, 
            { title: "A Tailorable Structural Composite for GCR and Albedo Neutron Protection on the Lunar Surface", award amount: 100000.000000 }, 
            { title: "Multi-Use Coating for Abrasion Prevention Wear Protection and Lunar Dust Removal", award amount: 100000.000000 }, 
            { title: "Advanced Composite Thrust Chambers for the Altair Lunar Lander", award amount: 100000.000000 }, 
            { title: "High Surface Area Iridium Anodes and Melt Containers for Molten Oxide Electrolysis", award amount: 600000.000000 }, 
            { title: "Multi-Use Coating for Abrasion Prevention Wear Protection and Lunar Dust Removal", award amount: 600000.000000 }, 
            { title: "Advanced Composite Thrust Chambers for the Altair Lunar Lander", award amount: 600000.000000 }, 
            { title: "Advanced Materials and Fabrication Techniques for the Orion Attitude Control Motor", award amount: 100000.000000 }, 
            { title: "High Chamber Pressure Light Weight Thrusters", award amount: 100000.000000 }, 
            { title: "Mass Production of Mature Lunar Regolith Simulant", award amount: 100000.000000 }, 
            { title: "Microchannel Thermo Catalytic Ignition for Advanced Mono- and Bipropellants", award amount: 100000.000000 }, 
            { title: "Production of Mature Highland Lunar Regolith Simulant", award amount: 100000.000000 }, 
            { title: "Non-Toxic HAN Monopropellant Propulsion", award amount: 100000.000000 }, 
            { title: "Improved Rhenium Thrust Chambers for In-Space Propulsion", award amount: 100000.000000 }, 
            { title: "Non-Toxic HAN Monopropellant Propulsion", award amount: 744427.000000 }, 
            { title: "Improved Rhenium Thrust Chambers for In-Space Propulsion", award amount: 750000.000000 }, 
            { title: "Fine Grained Tungsten Claddings for Cermet Based NTP Systems", award amount: 125000.000000 }, 
            { title: "Mesh Generation and Adaption for High Reynolds Number RANS Computations", award amount: 100000.000000 }, 
            { title: "Enhanced Carbon Nanotube Ultracapacitors", award amount: 99988.000000 }, 
            { title: "Mesh Generation and Adaption for High Reynolds Number RANS Computations", award amount: 600000.000000 }, 
            { title: "Prototype Carbon Nanotube Ultracapacitor", award amount: 599998.000000 }, 
            { title: "1 Gb Radiation Hardened Nonvolatile Memory Development", award amount: 100000.000000 }, 
            { title: "Advanced Nanostructured Cathode for Ultra High Specific Energy Lithium Ion Batteries", award amount: 123265.000000 }, 
            { title: "Nano-structures Enhanced Novel Composite Electrode Material for Batteries", award amount: 125000.000000 }, 
            { title: "Design and Development of a Compact and Rugged Phase and Fluorescence Microscope for Space Utilization", award amount: 199607.000000 }, 
            { title: "Rad-hard Location and Attitude Module (R-LAM)", award amount: 99996.000000 }, 
            { title: "Novel Solar Cell Nanotechnology for Improved Efficiency and Radiation Hardness", award amount: 69997.540000 }, 
            { title: "Prediction and Control of the Vibroacoustic Environment During a Launch Sequence", award amount: 69930.000000 }, 
            { title: "Oxygen-Methane Thruster", award amount: 69996.000000 }, 
            { title: "Modular Self-Rigidizing Lightweight Structures", award amount: 69980.000000 }, 
            { title: "Hydrogen Plasma Reduction of Lunar Regolith for In-Space Fabrication", award amount: 70000.000000 }, 
            { title: "3D Visualization System for Tracking and Identification of Objects", award amount: 69396.810000 }, 
            { title: "Computer Aided Design Tools for Extreme Environment Electronics", award amount: 69950.380000 }, 
            { title: "Hybrid Guidance System for Relative Navigation", award amount: 69990.000000 }, 
            { title: "Computational Tool for Aerothermal Environment Around Transatmospheric Vehicles", award amount: 99836.000000 }, 
            { title: "Improved Models and Tools for Prediction of Radiation Effects on Space Electronics in Wide Temperature Range", award amount: 99942.000000 }, 
            { title: "Multi-Physics Computational Modeling Tool for Materials Damage Assessment", award amount: 99618.000000 }, 
            { title: "High Performance Bipropellant Space Engines", award amount: 100000.000000 }, 
            { title: "Thermally Formed Deployable Self-Rigidizing Polyimide Structures", award amount: 70000.000000 }, 
            { title: "High Performance Capacitor for Pulsed Plasma Thruster", award amount: 69954.000000 }, 
            { title: "Optical Based Imaging for Protein Crystal Diagnostics", award amount: 69900.000000 }, 
            { title: "A Portable Non-invasive Detection/Identification System for Biological Pathogens", award amount: 70000.000000 }, 
            { title: "Analysis Tool For Launch-Induced Forcing Functions On Spacecraft Surfaces", award amount: 68854.000000 }, 
            { title: "High Strength Graphite Nanofiber-Doped Polymer Films", award amount: 70000.000000 }, 
            { title: "Novel Spectral Enhancement for Incipient Fault Detection of Rotating Machinery", award amount: 69984.000000 }, 
            { title: "Active Noncontact Shape Control of Preformed Membrane Mirrors and Antennas", award amount: 70000.000000 }, 
            { title: "Novel Biomatrix System for Human Tissue Growth &amp; Angiogenesis in Microgavity", award amount: 70000.000000 }, 
            { title: "XML Based Source Code to Requirements", award amount: 70000.000000 }, 
            { title: "Biomimetic Fabricated Solar Sail Technologies", award amount: 69994.000000 }, 
            { title: "High Performance Capacitor for Pulsed Plasma Thruster", award amount: 599971.000000 }, 
            { title: "Acoustic Prediction/Measurement Tool", award amount: 599060.250000 }, 
            { title: "Low-Cost Manufacturing Processes for Large Aperture Membrane Mirrors", award amount: 599999.440000 }, 
            { title: "Next-Generation Collaboration Tools to Support Telescience and Outreach", award amount: 599990.560000 }, 
            { title: "Novel Spectral Enhancement for Incipient Fault Detection of Rotating Machinery", award amount: 599663.000000 }, 
            { title: "A Portable Non-invasive Detection/Identification System for Biological Pathogens", award amount: 600000.000000 }, 
            { title: "Specific Impulse Analysis of Solid Materials for Ablative Laser Propulsion", award amount: 99958.000000 }, 
            { title: "A Solid Expellant Plasma Source/Contactor for Electrodynamic Tethers", award amount: 69989.000000 }, 
            { title: "Advanced Software For Design of Rocket Engine Turbopump Bearings", award amount: 69960.000000 }, 
            { title: "Vector Inversion Power Conditioning for High Energy Propulsion Concepts", award amount: 70000.000000 }, 
            { title: "Handheld Sensing Device for Pathogenic Detection", award amount: 70000.000000 }, 
            { title: "A Cooperative Multi-Robot Control Architecture", award amount: 69878.000000 }, 
            { title: "Multi-disciplinary Multiphase Flow Analyzer", award amount: 69923.000000 }, 
            { title: "Large Inflatable Self-Rigidizing Polymer Film Structures", award amount: 70000.000000 }, 
            { title: "Novel Advancements in Internet Based Real-Time Data Technologies", award amount: 69974.000000 }, 
            { title: "Robust High Temperature Containment Cartridges for Microgravity", award amount: 70000.000000 }, 
            { title: "Thermophotovoltaic and Thermionic Power Systems with Film Concentrators", award amount: 70000.000000 }, 
            { title: "Trojan Phage Crystallization System", award amount: 70000.000000 }, 
            { title: "Integration of High-Pressure Combustion Experiments and Simulations", award amount: 69997.000000 }, 
            { title: "Adjoint-Based Design Software Using Adaptive Finite Element Methods", award amount: 70000.000000 }, 
            { title: "Lightweight High Conductivity Metal Matrix Composite", award amount: 70000.000000 }, 
            { title: "Improved Materials and Processes for RF Antennas", award amount: 69992.000000 }, 
            { title: "A Solid Expellant Plasma Source/Contactor for Electrodynamic Tethers", award amount: 596253.000000 }, 
            { title: "Adjoint-Based Design Software Using Adaptive Finite Element Methods", award amount: 600000.000000 }, 
            { title: "A Cooperative Multi-Robot Control Architecture", award amount: 596952.000000 }, 
            { title: "Robust High Temperature Containment Cartridges for Microgravity", award amount: 599430.000000 }, 
            { title: "Multi-disciplinary Multiphase Flow Analyzer", award amount: 599031.000000 }, 
            { title: "Comprehensive Atomization/Spray Module for Advanced CFD Combustion Codes", award amount: 99969.000000 }, 
            { title: "Comprehensive Atomization/Spray Module for Advanced CFD Combustion Codes", award amount: 499873.000000 }, 
            { title: "Artificial Neural Net Chemistry Module for Large Eddy Simulations", award amount: 69923.300000 }, 
            { title: "Advanced Crew Escape System Simulation Tool for Future Launch Vehicles", award amount: 69917.000000 }, 
            { title: "Innovative Tungsten Alloys for Advanced Propulsion Systems", award amount: 70000.000000 }, 
            { title: "Enhanced Blackbody Sensors for the Quench Module Insert", award amount: 70000.000000 }, 
            { title: "Drag &amp;Drop Multiphysics &amp; Neural Net-based Lab-on-Chip Optimization Software", award amount: 69981.640000 }, 
            { title: "Grid-Based Distribution of Payload Video to Experimenters", award amount: 69931.000000 }, 
            { title: "Development of Tantalum Carbide for Microgravity Containment Cartridges", award amount: 70000.000000 }, 
            { title: "Rendezvous and Docking Sensor Suite", award amount: 69990.000000 }, 
            { title: "Inherently Stiff Membranes with Shape Memory", award amount: 70000.000000 }, 
            { title: "Wireless Handheld Device For Distributed Ground Operations", award amount: 69987.000000 }, 
            { title: "Next-Generation Collaboration Tools to Support Telescience and Outreach", award amount: 69967.000000 }, 
            { title: "Low-Cost Manufacturing Processes for Large Aperture Membrane Mirrors", award amount: 70000.000000 }, 
            { title: "Novel Biomatrix System for Human Tissue Growth &amp; Angiogenesis in Microgavity", award amount: 600000.000000 }, 
            { title: "Specific Impulse Analysis of Solid Materials for Ablative Laser Propulsion", award amount: 499461.000000 }, 
            { title: "Development of Boundary Vorticity Dynamics Based Closed Loop Flow Control", award amount: 69990.000000 }, 
            { title: "A Collaborative Software Tool to Improve the Dynamic Testing Process ", award amount: 69611.000000 }, 
            { title: "Trojan Phage Crystallization System", award amount: 600000.000000 }, 
            { title: "Thermophotovoltaic and Thermionic Power Systems with Film Concentrators", award amount: 599957.000000 }, 
            { title: "Large Inflatable Self-Rigidizing Polymer Film Structures", award amount: 599984.000000 }, 
            { title: "A New Methodology for Calculating Launch Vehicle Ascent Loads", award amount: 69415.000000 }, 
            { title: "Engine Test Stand Design Constraints Expert System", award amount: 70000.000000 }, 
            { title: "Effect of Ambipolar Potential on the Propulsive Performance of the GDM Plasma Thruster", award amount: 99973.000000 }, 
            { title: "Constellation C3I Crew-Ground-Experimenter-Developer Collaboration Services", award amount: 69759.000000 }, 
            { title: "Grid-Based Distribution of Payload Video to Experimenters", award amount: 599981.000000 }, 
            { title: "Innovative Tungsten Alloys for Advanced Propulsion Systems", award amount: 600000.000000 }, 
            { title: "Enhanced Blackbody Sensors for the Quench Module Insert", award amount: 599997.000000 }, 
            { title: "Rendezvous and Docking Sensor Suite", award amount: 599994.000000 }, 
            { title: "Drag &amp; Drop Mixed-Methodology Based Lab-on-Chip Design Optimization Software", award amount: 599959.600000 }, 
            { title: "A Novel Microfluidic Device for Fully Automated Extraction of RNA from Cell Cultures", award amount: 69958.940000 }, 
            { title: "Multiparameter Fiber Optic Sensor Suite for Structures", award amount: 67782.000000 }, 
            { title: "Data Reduction and Rapid Analysis of Hyperspectral Data Sets", award amount: 69944.000000 }, 
            { title: "Altitude Compensating Nozzle Design Tool", award amount: 69809.000000 }, 
            { title: "Altitude Compensating Nozzle Transonic Performance Flight Demonstration", award amount: 69919.770000 }, 
            { title: "Neural Network Enhanced Structure Determination of Osteoporosis Immune System and Radiation Repair Proteins", award amount: 70000.000000 }, 
            { title: "A Novel Radiation Shielding Material", award amount: 70000.000000 }, 
            { title: "Smart Crucibles for Materials Processing in Microgravity", award amount: 70000.000000 }, 
            { title: "Multi-Scale (nano-to-device) Multi-Physics Software For Design of Nanobiosystems", award amount: 69990.440000 }, 
            { title: "Electrophoretic Focusing: An Alternative to Capillary Electrophoresis", award amount: 69774.000000 }, 
            { title: "Ultra-Lightweight Large Aperture Support Structures", award amount: 69986.000000 }, 
            { title: "High Order Wavelet-Based Multiresolution Technology for Airframe Noise Prediction", award amount: 69975.000000 }, 
            { title: "High Order Wavelet-Based Multiresolution Technology for Airframe Noise Prediction", award amount: 599923.000000 }, 
            { title: "A Novel Microfluidic Device for Fully Automated Extraction of RNA from Cell Cultures", award amount: 599903.440000 }, 
            { title: "Smart Crucibles and Heat Pipes", award amount: 600000.000000 }, 
            { title: "A Novel Radiation Shielding Material", award amount: 600000.000000 }, 
            { title: "Neural Network Enhanced Structure Determination of Osteoporosis Immune System and Radiation Repair Proteins", award amount: 600000.000000 }, 
            { title: "Effect of Ambipolar Potential on the Propulsive Performance of the GDM Plasma Thruster", award amount: 599613.000000 }, 
            { title: "Aeroelastic Simulation Tool for Inflatable Ballute Aerocapture", award amount: 69965.000000 }, 
            { title: "High Energy Low Temperature Gelled Bi-Propellant Formulation for Long-Duration In-Space Propulsion", award amount: 69914.000000 }, 
            { title: "Understanding and Mitigating Adverse Health Effects in Space Using A System Physiology Software", award amount: 69957.350000 }, 
            { title: "Unstructured Mesh Movement and Viscous Mesh Generation for CFD-Based Design Optimization", award amount: 70000.000000 }, 
            { title: "Radiation Shielding Using Thermally Insulating Spheres", award amount: 69779.810000 }, 
            { title: "Thin Film Flat Panel Off-Axis Solar Concentrator with Flux  Distribution", award amount: 69962.000000 }, 
            { title: "Novel Non-Intrusive Vibration Monitoring System for Turbopumps", award amount: 69994.000000 }, 
            { title: "Aeroelastic Simulation Tool for Inflatable Ballute Aerocapture", award amount: 50000.000000 }, 
            { title: "Thin Film Flat Panel Off-Axis Solar Concentrator with Flux  Distribution", award amount: 50000.000000 }, 
            { title: "Unstructured Mesh Movement and Viscous Mesh Generation for CFD-Based Design Optimization", award amount: 600000.000000 }, 
            { title: "Novel Non-Intrusive Vibration Monitoring System for Turbopumps", award amount: 50000.000000 }, 
            { title: "High Energy Low Temperature Gelled Bi-Propellant Formulation for Long-Duration In-Space Propulsion", award amount: 50000.000000 }, 
            { title: "Versatile Wireless Data Net", award amount: 99845.430000 }, 
            { title: "Practical Multi-Disciplinary Analysis Tools for Combustion Devices", award amount: 99999.000000 }, 
            { title: "Nanostructured Tungsten Rhenium Components for Propulsion Systems", award amount: 100000.000000 }, 
            { title: "Improved Understanding of Space Radiation Effects on Exploration Electronics by Advanced Modeling of Nanoscale Devices and Novel Materials", award amount: 99994.000000 }, 
            { title: "Fine Grained Tungsten Claddings for Cermet Based NTP Systems", award amount: 750000.000000 }, 
            { title: "Low-Cost Manufacturing Technique for Advanced Regenerative Cooling for In-Space Cryogenic Engines", award amount: 750000.000000 }, 
            { title: "Multiple High-Fidelity Modeling Tools for Metal Additive Manufacturing Process Development", award amount: 124715.000000 }, 
            { title: "Unstructured High-Order Scheme Module with Low Dissipation Flux Difference Splitting for Noise Prediction", award amount: 124859.000000 }, 
            { title: "Development of Hot Structures Materials for Inflatable Heat Shield", award amount: 124926.000000 }, 
            { title: "Radiation-Hardening of Best-In-Class SiGe Mixed-Signal and RF Electronics for Ultra-Wide Temperature Range", award amount: 123251.000000 }, 
            { title: "Nonlinear Parameter-Varying AeroServoElastic Reduced Order Model for Aerostructural Sensing and Control", award amount: 124800.000000 }, 
            { title: "High-Efficiency Rad-Hard Ultra-Thin Si Photovoltaic Cell Technology for Space", award amount: 124968.000000 }, 
            { title: "Reduced Cost Composite Hot Structures with Oxidation Protection", award amount: 125000.000000 }, 
            { title: "100-lbf Non-Toxic Storable Liquid Propulsion", award amount: 125000.000000 }, 
            { title: "Multiple High-Fidelity Modeling Tools for Metal Additive Manufacturing Process Development", award amount: 749991.000000 }, 
            { title: "Radiation-Hardening of Best-In-Class SiGe Mixed-Signal and RF Electronics for Ultra-Wide Temperature Range", award amount: 749918.000000 }, 
            { title: "Nonlinear Parameter-Varying AeroServoElastic Reduced Order Model for Aerostructural Sensing and Control", award amount: 949848.000000 }, 
            { title: "Improved Forecasting of Solar Particle Events and their Effects on Space Electronics", award amount: 124982.000000 }, 
            { title: "Integrated Reacting Fluid Dynamics and Predictive Materials Degradation Models for Propulsion System Conditions", award amount: 124988.000000 }, 
            { title: "Microwave Extraction of Water from Boreholes in Regolith", award amount: 124958.000000 }, 
            { title: "Thermodynamically Consistent Electrochemical Models for Accelerating Development and Qualification of Power Generation and Storage Systems", award amount: 124949.000000 }, 
            { title: "Lightweight Inflatable Structural Airlock (LISA)", award amount: 124952.000000 }, 
            { title: "Variable Fidelity AeroPropulsoServoElasticity Analysis Tool", award amount: 124977.000000 }, 
            { title: "Cubesat Collapsible Composite Antenna", award amount: 124945.000000 }, 
            { title: "Thermo-Catalytic Ignition of Cryogenic Oxygen-Methane", award amount: 125000.000000 }, 
            { title: "Metallic Joining to Advanced Ceramic Composites", award amount: 125000.000000 }, 
            { title: "Advanced Zirconium Carbide Tie-Tubes for NTP", award amount: 125000.000000 }, 
            { title: "Slow and Fast Light", award amount: 124979.000000 }, 
            { title: "Optimization Of Fuel Consumption Using Atmospheric Vertical Air Currents", award amount: 124997.000000 }, 
            { title: "SparkRS - Spark for Remote Sensing", award amount: 123143.000000 }, 
            { title: "Advanced Aerodynamic Analysis For Propulsion Airframe Integration", award amount: 123473.000000 }, 
            { title: "Power Generating Coverings and Casings", award amount: 749926.000000 }, 
            { title: "MEMS Based Solutions for an Integrated and Miniaturized Multi-Spectrum Energy Harvesting and Conservation System", award amount: 750000.000000 }, 
            { title: "Particle Flow Physics Modeling for Extreme Environments", award amount: 746289.000000 }, 
            { title: "High-Fidelity Prediction of Launch Vehicle Lift-off Acoustic Environment", award amount: 749861.000000 }, 
            { title: "100-lbf Non-Toxic Storable Liquid Propulsion", award amount: 749902.000000 }, 
            { title: "In-Space LOX/Methane Pintle Propulsion Engine (LMPPE) Evaluation and Demonstration", award amount: 124823.000000 }, 
            { title: "Lightweight Inflatable Structural Airlock (LISA)", award amount: 749897.000000 }, 
            { title: "An Additive Manufacturing Technique for the Production of Electronic Circuits", award amount: 124663.000000 }, 
            { title: "Unified In-Space Propulsion Framework for Prediction of Plume-Induced Spacecraft Environments", award amount: 124952.000000 }, 
            { title: "Prediction of Strutural Response and Fluid-Induced Vibration in Turbomachinery", award amount: 124986.000000 }, 
            { title: "Sustainable Water Purification", award amount: 124868.000000 }, 
            { title: "Green Monopropellant Propulsion for Small Spacecrafts", award amount: 125000.000000 }, 
            { title: "Multipulse Solid Rocket Motors for MAV", award amount: 124758.000000 }, 
            { title: "Characterization and Mitigation of Radiation and High Temperature Effects in SiC Power Electronics", award amount: 124989.000000 }, 
            { title: "Propellant Gelation for Green In-Space Propulsion", award amount: 123123.000000 }, 
            { title: "Additive Manufacturing of Telescope Mirrors", award amount: 125000.000000 }, 
            { title: "Additively Manufactured Monolithic Catalyst Bed for Green Propellants", award amount: 125000.000000 }, 
            { title: "Additively Manufactured Low Power Thrusters for Secondary Payloads", award amount: 125000.000000 }, 
            { title: "Joining of Tungsten Cermet Nuclear Fuel", award amount: 125000.000000 }, 
            { title: "Development of Diamond Vacuum Differential Amplifier for Harsh Environment Power Electronics", award amount: 121862.000000 }, 
            { title: "Robust Prediction of High Lift Using Surface Vorticity", award amount: 125000.000000 }, 
            { title: "Improved Forecasting of Solar Particle Events and their Effects on Space Electronics", award amount: 749933.000000 }, 
            { title: "Metallic Joining to Advanced Ceramic Composites", award amount: 750000.000000 }, 
            { title: "Joining of Tungsten Cermet Nuclear Fuel", award amount: 750000.000000 }, 
            { title: "Characterization and Mitigation of Radiation and High Temperature Effects in SiC Power Electronics", award amount: 749900.000000 }, 
            { title: "Green Monopropellant Propulsion for Small Spacecrafts", award amount: 750000.000000 }, 
            { title: "Development of Diamond Vacuum Differential Amplifier for Harsh Environment Power Electronics", award amount: 750000.000000 }, 
            { title: "Robust Prediction of High Lift Using Surface Vorticity", award amount: 750000.000000 }, 
            { title: "Multiphase Modeling of Solid Rocket Motor Internal Environment", award amount: 124928.000000 }, 
            { title: "Transient Acoustic Environment Prediction Tool for Launch Vehicles in Motion during Early Lift-Off", award amount: 124981.000000 }, 
            { title: "Prediction and Control of Selective Laser Melting Product Microstructure", award amount: 124996.000000 }, 
            { title: "High Fidelity Tool for Noise Source Identification", award amount: 124904.000000 }, 
            { title: "A Software Tool for High-Order Element Mesh Generation", award amount: 124904.000000 }, 
            { title: "Integrated Fluid and Materials Modeling of Environmental Barrier Coatings", award amount: 124937.000000 }, 
            { title: "Non-Intrusive Computational Method and Uncertainty Quantification Tool for Isolator Operability Calculations", award amount: 124914.000000 }, 
            { title: "Radiation and High Temperature Tolerant GaN Power Electronics", award amount: 124902.000000 }, 
            { title: "Hybrid Propulsion Technology for Robotic Science Missions", award amount: 124994.000000 }, 
            { title: "Evaluation of Multifunctional Radiation Shielding Material Against Long Duration Space Environment - Utilization of MISSE-FF", award amount: 110486.000000 }, 
            { title: "Unified In-Space Propulsion Framework for Prediction of Plume-Induced Spacecraft Environments", award amount: 749989.000000 }, 
            { title: "Non-Intrusive Computational Method and Uncertainty Quantification Tool for Isolator Operability Calculations", award amount: 749976.000000 }, 
            { title: "Integrated Fluid and Materials Modeling of Environmental Barrier Coatings", award amount: 749883.000000 }, 
            { title: "An Additive Manufacturing Technique for the Production of Electronic Circuits", award amount: 736492.000000 }, 
            { title: "Evaluation of Multifunctional Radiation Shielding Material Against Long Duration Space Environment - Utilization of MISSE-FF", award amount: 749975.000000 }, 
            { title: "Towards Exascale Computing of Compressible Flows using LBM", award amount: 124955.000000 }, 
            { title: "Additively Manufactured Propellant Tanks with Integral Propellant Acquisition Device", award amount: 125000.000000 }, 
            { title: "High Temperature Oxidation Resistant Coatings Integrated with Carbon/Carbon Hot Structures", award amount: 124728.000000 }, 
            { title: "Using MISSE-FF to Determine the Effect of the Space Environment on Advanced Thermal Protection Coatings", award amount: 124998.000000 }, 
            { title: "Low Emission Lean Fully Premixed (LFP) Injector/Combustor Development", award amount: 124894.000000 }, 
            { title: "Multi-Fidelity Surrogate Modeling for Computational and Experimental Data Consolidation", award amount: 124915.000000 }, 
            { title: "Packaging and Manufacturing Processes to Enable Production of Very Large Solar Sails for Next Generation Missions", award amount: 124637.000000 }, 
            { title: "An Intelligent Framework to Develop Adaptive Parametric Reduced Order Model Database for Aerostructural Control", award amount: 124798.000000 }, 
            { title: "Space Durability Testing via MISSE-FF of CORIN XLS Polyimide with Increased Flexibility and Tear Resistance", award amount: 124815.000000 }, 
            { title: "Characterization of a Multi-Kilometer Long Tether Deployment", award amount: 102367.000000 }, 
            { title: "Multiphase Modeling of Solid Rocket Motor Internal Environment", award amount: 749859.000000 }, 
            { title: "Transient Acoustic Environment Prediction Tool for Launch Vehicles in Motion During Early Lift-Off", award amount: 749891.000000 }, 
            { title: "A Scalable Gas-Particle Flow Simulation Tool for Lander Plume-Surface Interaction and Debris Prediction", award amount: 124946.000000 }, 
            { title: "Hybrid Propulsion Technology for Robotic Science Missions", award amount: 749229.000000 }, 
            { title: "Additive Manufacture of Refractory Metal Propulsion Components", award amount: 124838.000000 }, 
            { title: "Prediction of Plume Induced Rock Fracture for Landers", award amount: 124995.000000 }, 
            { title: "Using MISSE-FF to Determine the Effect of the Space Environment on Advanced Thermal Protection Coatings", award amount: 749948.000000 }, 
            { title: "Packaging and Manufacturing Processes to Enable Production of Very Large Solar Sails for Next Generation Missions", award amount: 749911.000000 }, 
            { title: "Space Durability Testing via MISSE-FF of CORIN XLS Polyimide with Increased Flexibility and Tear Resistance", award amount: 749967.000000 }, 
            { title: "An Intelligent Framework to Develop Adaptive Parametric Reduced Order Model Database for Aerostructural Control", award amount: 745398.000000 }, 
            { title: "Refractory Metal Coated Uranium Nitride Fuel for Nuclear Thermal Propulsion", award amount: 124999.000000 }, 
            { title: "Highly Compatible Additively Manufactured LOX Injectors", award amount: 124804.000000 }, 
            { title: "Measurement and Modeling of High Speed Polydisperse Granular Flow Under Plume/Surface Interaction Conditions", award amount: 124882.000000 }, 
            { title: "Simple Reliable Retractable Lunar Lander Solar Array", award amount: 124977.000000 }, 
            { title: "Demonstration of Dual Mode Ionic Liquid Propulsion", award amount: 124965.000000 }, 
            { title: "Dual Mode Green Monopropellant Propulsion System for Interplanetary Missions", award amount: 125000.000000 }, 
            { title: "Air Vehicle Gust Response analysis for Conceptual Design", award amount: 124998.000000 }, 
            { title: "Testing of COTS Systems in Space", award amount: 124951.000000 }, 
            { title: "Dispersion Strengthened Refractory Metal Claddings for NTP", award amount: 124999.000000 }, 
            { title: "Plume-Surface Interaction in Rarefied Environments", award amount: 124879.000000 }, 
            { title: "Silicon Carbide-based Power Electronics for Small Fission Reactors", award amount: 124951.000000 }, 
            { title: "Highly Compatible Additively Manufactured LOX Injectors", award amount: 0.000000 }, 
            { title: "Refractory Metal Coated Uranium Nitride Fuel for Nuclear Thermal Propulsion", award amount: 750000.000000 }, 
            { title: "Measurement and Modeling of High Speed Polydisperse Granular Flow Under Plume/Surface Interaction Conditions", award amount: NaN }, 
            { title: "A Scalable Gas-Particle Flow Simulation Tool for Lander Plume-Surface Interaction and Debris Prediction", award amount: 749955.000000 }, 
            { title: "An Additively Manufactured Leak-Proof NTO Swivel", award amount: 0.000000 }, 
            { title: "Bi-Fold Fan DragSail with Surface Area Modulation Capability", award amount: 0.000000 }, 
            { title: "Expedient Formulator for Generative Evaluation (XFORGE)", award amount: 0.000000 }, 
            { title: "An Intelligent Framework for Integrated State-Consistent AeroServoElastic Reduced Order Model Development and Control Synthesis", award amount: 0.000000 }, 
            { title: "Additive Friction Stir Deposition for In-Space Manufacturing", award amount: 0.000000 }, 
            { title: "Space Weather Forecasting Toolset to Support Operations", award amount: 0.000000 }, 
            { title: "Testing of COTS Systems in Space Radiation Environments", award amount: 124986.000000 }, 
            { title: "Early-Design Aeroacoustics Prediction for Distributed Electric Propulsion Vehicles using FlightStream", award amount: 124988.000000 }, 
          ]);
        }}
      >
        Click Me!
      </Button>
    </>
  );
}
